import { TrackPreset, SpatialSceneState } from './types';

export const TECHNO_PRESETS: TrackPreset[] = [
  {
    id: 'peak-time-techno',
    name: 'Peak Time Energy',
    genre: 'Peak Time Techno',
    bpm: 132,
    key: 'C Minor (Acid)',
    description: 'Driving peak-time weapon with a powerful, round low-end kick, relentless offbeat hats, and a sharp rhythmic synthesizer sequence.',
    patterns: {
      channel1: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      channel2: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true],
      channel3: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel4: [true, false, true, true, false, true, false, true, true, false, true, false, true, true, false, false],
      channel5: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel6: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel7: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel8: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    },
    synthNotes: [0, 2, 3, 4, 1, 3, 2, 4, 3, 1, 5, 2, 4, 3, 0, 0],
    cutoff: 950,
    resonance: 8,
    delayTime: 0.25,
    decay: 0.16,
  },
  {
    id: 'goa',
    name: 'Goa Sunrise',
    genre: 'Goa Trance',
    bpm: 140,
    key: 'F# Phrygian',
    description: 'Nostalgic 140 BPM acid-infused Goa trance. Features organic melodic scales, resonant synth sweeps, and high-frequency driving tribal energy.',
    patterns: {
      channel1: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      channel2: [false, false, true, false, false, false, true, false, false, false, true, false, true, true, true, false],
      channel3: [false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false],
      channel4: [false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true],
      channel5: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel6: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel7: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel8: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    },
    synthNotes: [0, 1, 2, 3, 0, 3, 2, 1, 0, 2, 4, 5, 0, 5, 4, 2],
    cutoff: 1100,
    resonance: 10,
    delayTime: 0.33,
    decay: 0.18,
  },
  {
    id: 'psy',
    name: 'Psychedelic Portal',
    genre: 'Psy Trance',
    bpm: 138,
    key: 'A Minor Pentatonic',
    description: 'Immersive psychedelic trance loop with highly modulated offbeat basslines, hypnotic squelches, and cosmic echoes.',
    patterns: {
      channel1: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      channel2: [false, false, true, false, false, false, true, true, false, false, true, false, false, false, true, false],
      channel3: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel4: [false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true],
      channel5: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel6: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel7: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel8: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    },
    synthNotes: [0, 3, 3, 0, 0, 4, 4, 0, 0, 5, 5, 0, 0, 7, 7, 3],
    cutoff: 650,
    resonance: 11,
    delayTime: 0.25,
    decay: 0.12,
  },
  {
    id: 'psytrance',
    name: 'Vini Vici Tribeland',
    genre: 'Psytrance',
    bpm: 142,
    key: 'F# Phrygian',
    description: 'High-octane, triple-gated "KBBB" psytrance rhythm. The bassline gallops perfectly right after each powerful punchy kick.',
    patterns: {
      channel1: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      channel2: [false, false, true, false, false, true, true, false, false, false, true, false, true, false, true, true],
      channel3: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel4: [false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true],
      channel5: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel6: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel7: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel8: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    },
    synthNotes: [0, 0, 0, 0, 0, 1, 1, 1, 0, 2, 2, 2, 0, 1, 1, 2],
    cutoff: 550,
    resonance: 6,
    delayTime: 0.125,
    decay: 0.14,
  },
  {
    id: 'industrial',
    name: 'Schranz Factory',
    genre: 'Industrial Techno',
    bpm: 140,
    key: 'F# Phrygian',
    description: 'Aggressive, distorted, and heavy warehouse techno with overdriven kicks on almost every step and screeching high-resonance modulations.',
    patterns: {
      channel1: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true],
      channel2: [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      channel3: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, true],
      channel4: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
      channel5: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel6: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel7: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel8: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    },
    synthNotes: [0, 1, 0, 1, 2, 1, 0, 3, 2, 1, 0, 4, 3, 2, 1, 0],
    cutoff: 1250,
    resonance: 9,
    delayTime: 0.125,
    decay: 0.08,
  },
  {
    id: 'bounce',
    name: 'Melbourne Bounce Club',
    genre: 'Bounce',
    bpm: 128,
    key: 'A Minor Pentatonic',
    description: 'An infectious, upbeat Australian bounce rhythm with a distinct offbeat "woody" bass jump and upbeat energy.',
    patterns: {
      channel1: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      channel2: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
      channel3: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel4: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true],
      channel5: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel6: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel7: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel8: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    },
    synthNotes: [0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 7, 4],
    cutoff: 720,
    resonance: 7,
    delayTime: 0.25,
    decay: 0.22,
  },
  {
    id: 'hardbounce',
    name: 'Hardstyle Bounce Machine',
    genre: 'Hardbounce',
    bpm: 145,
    key: 'C Minor (Acid)',
    description: 'Extremely energetic hard bounce combining highly resonant acid basslines, 145 BPM tempo, and rapid upbeat synth sweeps.',
    patterns: {
      channel1: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, true],
      channel2: [false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true],
      channel3: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel4: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true],
      channel5: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel6: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel7: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel8: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    },
    synthNotes: [0, 2, 4, 2, 0, 3, 5, 3, 0, 4, 6, 4, 1, 3, 5, 7],
    cutoff: 1100,
    resonance: 13,
    delayTime: 0.25,
    decay: 0.15,
  },
  {
    id: 'tekk',
    name: 'Hardtekk Overload',
    genre: 'Tekk',
    bpm: 148,
    key: 'C Minor (Acid)',
    description: 'A brutal 148 BPM tekk rhythm featuring heavy pounding distorted low kicks, rapid hats, and metallic screeching industrial synthesizers.',
    patterns: {
      channel1: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true],
      channel2: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true],
      channel3: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel4: [true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true],
      channel5: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      channel6: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel7: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      channel8: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    },
    synthNotes: [0, 1, 0, 1, 2, 1, 0, 3, 2, 1, 0, 4, 3, 2, 1, 0],
    cutoff: 1350,
    resonance: 14,
    delayTime: 0.125,
    decay: 0.06,
  }
];

// ============================================================================
// spatialMONK – Scene-Presets (WhitePaper Abschnitt 7)
// ============================================================================

export const DEFAULT_SPATIAL_SCENE: SpatialSceneState = {
  version: 'spatialMONK-v1',
  global: { quality: 'medium', listenerRot: 0, masterGain: 1, hrtf: 'default', layout: '10.0' },
  sources: [
    { id: 1, name: 'Kick', az: 0, el: 0, dist: 0.8, gain: 0.9, muted: false, color: '#f43f5e', track: 'channel1' },
    { id: 2, name: 'Hats', az: 35, el: 0, dist: 1.2, gain: 0.7, muted: false, color: '#10b981', track: 'channel2' },
    { id: 3, name: 'Clap', az: -40, el: 0, dist: 1.0, gain: 0.7, muted: false, color: '#f59e0b', track: 'channel3' },
    { id: 4, name: 'Bass', az: 0, el: 0, dist: 1.5, gain: 0.95, muted: false, color: '#22d3ee', track: 'channel7' },
    { id: 5, name: 'Lead', az: 25, el: 0, dist: 1.3, gain: 0.85, muted: false, color: '#f97316', track: 'channel8' },
  ],
};

export const SPATIAL_SCENE_PRESETS: SpatialSceneState[] = [
  DEFAULT_SPATIAL_SCENE,
  {
    version: 'spatialMONK-v1',
    global: { quality: 'low', listenerRot: 0, masterGain: 1, hrtf: 'default', layout: '2.0' },
    sources: [
      { id: 1, name: 'Lead', az: -25, el: 0, dist: 1.1, gain: 0.95, muted: false, color: '#f97316', track: 'channel8' },
      { id: 2, name: 'Pad', az: 90, el: 0, dist: 2.5, gain: 0.6, muted: false, color: '#a78bfa', track: 'channel4' },
    ],
  },
];
